Feat/adding sapphire
torusresearch/torus-direct-android-sdk pull request #27
Opened 2023-08-22 10:43 UTC by grvgoel81

Feat/adding sapphire

2024-08-16 09:55 UTC, metalurgical requested changes

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +        TorusPublicKey torusPublicKey = torusUtils.getPublicAddress(getTorusNodeEndpoints(details), verifier, verifierId, null);
```suggestion
```

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +        }
Can't be null, will throw an error if it can't produce a valid `TorusKey`.
```suggestion
```

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +        TorusKey shareResponse = torusUtils.retrieveShares(getTorusNodeEndpoints(details), verifier, verifierParams, idToken, null);
```suggestion
return torusUtils.retrieveShares(getTorusNodeEndpoints(details), verifier, verifierParams, idToken, null);
```

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +    }
Split this into two functions, each returning their relevant variable.

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/CustomAuthArgs.java
> +    public CustomAuthArgs(String browserRedirectUri, Web3AuthNetwork network, String _redirectUri, String clientId, boolean enableOneKey) {
There are more params required here.

```
serverTimeOffset,
metadataUrl,
apiKey
etc...
```

2024-08-16 09:55 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/TorusAggregateLoginResponse.java
> +    public TorusAggregateLoginResponse(TorusVerifierUnionResponse[] userInfo, BigInteger privateKey, String publicAddress, org.torusresearch.torusutils.types.common.TorusKey retrieveSharesResponse) {
```suggestion
    public TorusAggregateLoginResponse(TorusVerifierUnionResponse[] userInfo, BigInteger privateKey, String publicAddress, TorusKey retrieveSharesResponse) {
```

2024-08-20 07:19 UTC, metalurgical requested changes
Looking better, please see new comments.

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/TorusLoginResponse.java
> +    public org.torusresearch.torusutils.types.common.TorusKey getRetrieveSharesResponse() {
```suggestion
    public TorusKey getRetrieveSharesResponse() {
```

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/TorusLoginResponse.java
> +    public TorusLoginResponse(TorusVerifierUnionResponse userInfo, BigInteger privateKey, String publicAddress, org.torusresearch.torusutils.types.common.TorusKey retrieveSharesResponse, FinalKeyData
```suggestion
    public TorusLoginResponse(TorusVerifierUnionResponse userInfo, BigInteger privateKey, String publicAddress, TorusKey retrieveSharesResponse, FinalKeyData finalKeyData,
```

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/CustomAuthArgs.java
> +        }
This should not be allowed to be null or empty, not so?

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>          this.verify_params[index] = verify_param;
This is an array. What if the index is > allocated size?

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>  public class AggregateVerifierParams {
We should rather construct this object completely in the constructor vs setting individual items.

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +    private String[] getTorusNode_Endpoints(NodeDetails nodeDetails) {
```suggestion
    private String[] getTorusNodeEndpoints(NodeDetails nodeDetails) {
```

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +        VerifierParams aggregateVerifierParamsHashMap = new VerifierParams(aggregateVerifierParams.getVerifier_id(), null,
Probably would want to rename this, it is no longer a hash map

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +            TorusKey retrieveSharesResponse = pair.second;
Think the name here was correct, we're not getting a share back but the final key
```suggestion
            TorusKey torusKey = pair.second; 
```

2024-08-20 07:19 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/CustomAuth.java
> +    public TorusKey getTorusKey(String verifier, String verifierId, VerifierParams verifierParams, String idToken) throws Exception {
Good simplification

2024-09-02 08:41 UTC, chaitanyapotti approved these changes
lgtm

2024-09-02 08:41 UTC, merged

2024-09-02 09:18 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>  public class AggregateVerifierParams {
This still needs to be resolved.

2024-09-02 09:18 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>          this.verify_params[index] = verify_param;
This still needs to be resolved.

2024-09-02 09:42 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>          this.verify_params[index] = verify_param;
resolved in #31

2024-09-02 09:42 UTC, metalurgical commented on sdk/src/main/java/org/torusresearch/customauth/types/AggregateVerifierParams.java
>  public class AggregateVerifierParams {
resolved in #31